version:0.1

 phases:
   pre_build:
     commands:
         - npm install
        build:
        commands:
         - npm run build
         

  artifiacts:
     files:
       - public/**/*
       - src/**/*
       - package.json
       - appspec.yml
       - scripts/**/*
     discard-paths : no
     base-directory : build     